=== PletkaDaniil/WEB_Project/dtd/technical_specification.dtd
<!ELEMENT TechnicalSpecification (Overview, Roles, Data, TechnicalSpecifications)>
<!ELEMENT Overview (Description, Version, CreatedBy, Date)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT CreatedBy (#PCDATA)>
<!ELEMENT Date (#PCDATA)>

<!ELEMENT Roles (Role+)>
<!ELEMENT Role (Tool, Responsibility+)>
<!ELEMENT Tool (#PCDATA)>
<!ELEMENT Responsibility (#PCDATA)>

<!ELEMENT Data (Elements)>
<!ELEMENT Elements (Element+)>
<!ELEMENT Element (Description, ChildElements?, Attributes?)>
<!ATTLIST Element name CDATA #REQUIRED>
<!ELEMENT ChildElements (Element+)>
<!ELEMENT Attributes (Attribute+)>
<!ELEMENT Attribute (Type, Required, Description)>
<!ATTLIST Attribute name CDATA #REQUIRED>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Required (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!ELEMENT TechnicalSpecifications (Type, DevTools, DBMS, Testing, Deployment)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT DevTools (Dev+)>
<!ELEMENT Dev (#PCDATA)>
<!ELEMENT DBMS (Tool, Reasoning)>
<!ELEMENT Tool (#PCDATA)>
<!ELEMENT Reasoning (#PCDATA)>
<!ELEMENT Testing (Test+)>
<!ELEMENT Test (#PCDATA)>

<!ELEMENT Deployment (Containerization)>
<!ELEMENT Containerization (Tool, Description, Dockerfile)>
<!ELEMENT Dockerfile (BaseImage, WorkingDirectory, KeySteps)>
<!ELEMENT BaseImage (#PCDATA)>
<!ELEMENT WorkingDirectory (#PCDATA)>
<!ELEMENT KeySteps (Step+)>
<!ELEMENT Step (#PCDATA)>

=== PletkaDaniil/WEB_Project/dtd/technical_specification.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TechnicalSpecification SYSTEM "technical_specification.dtd">

<TechnicalSpecification>
    <Overview>
        <Description>
            Technical specification for the database of a service that allows users to find movie recommendations based on their interests.
            This is achieved through posts, comments, likes on posts, as well as tags and a large selection of movies.There is also logging to record user actions on the website.
        </Description>
        <Version>1.0</Version>
        <CreatedBy>Pletka Daniil</CreatedBy>
        <Date>2024-12-17</Date>
    </Overview>

    <Roles>
        <Role>
            <Tool>User</Tool>

            <Responsibility>A user can create, comment and like posts with recommendations for movies, actors and more. There is also a tagging system that allows for easy searching of desired recommendations.The service includes a built-in recommendation system that suggests content based on user preferences, such as a liked plot, actor, rating and more.</Responsibility>
        </Role>
    </Roles>

    <Data>
        <Elements>
        <Element name="Users">
            <Description>Contains information about the service's users.</Description>
            <ChildElements>
                <Element name="User">
                    <Description>User of the service.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the user.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
                        <Element name="Email">
                            <Description>User's email.</Description>
                        </Element>
                        <Element name="Username">
                            <Description>User's username.</Description>
                        </Element>
                        <Element name="Password">
                            <Description>User's password.</Description>
                        </Element>
                        <Element name="Date_Created">
                            <Description>User's creation date.</Description>
                        </Element>
                    </ChildElements>
                </Element>
            </ChildElements>
        </Element>

        <Element name="Posts">
            <Description>Contains information about users' posts.</Description>
            <ChildElements>
                <Element name="Post">
                    <Description>User's post.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the post.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
                        <Element name="Text">
                            <Description>Text of the post.</Description>
                        </Element>
                        <Element name="Date_Created">
                            <Description>Post creation date.</Description>
                        </Element>
                        <Element name="Author">
                            <Description>User's identifier who created the post.</Description>
                        </Element>
                    </ChildElements>
                </Element>
            </ChildElements>
        </Element>

        <Element name="Comments">
            <Description>Contains user comments on posts.</Description>
            <ChildElements>
                <Element name="Comment">
                    <Description>User's comment.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the comment.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
                        <Element name="Text">
                            <Description>Comment text.</Description>
                        </Element>
                        <Element name="Date_Created">
                            <Description>Comment creation date.</Description>
                        </Element>
                        <Element name="Author">
                            <Description>User identifier who created the comment.</Description>
                        </Element>
                        <Element name="Post_ID">
                            <Description>Post identifier for the comment.</Description>
                        </Element>
                    </ChildElements>
                </Element>
            </ChildElements>
        </Element>

        <Element name="Likes">
            <Description>Contains information about user likes on posts.</Description>
            <ChildElements>
                <Element name="Like">
                    <Description>User's like.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the like.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
                        <Element name="Date_Created">
                            <Description>Like creation date.</Description>
                        </Element>
                        <Element name="Author">
                            <Description>User identifier who liked the post.</Description>
                        </Element>
                        <Element name="Post_ID">
                            <Description>Post identifier for the like.</Description>
                        </Element>
                    </ChildElements>
                </Element>
            </ChildElements>
        </Element>

        <Element name="Tags">
            <Description>Contains information about tags related to posts.</Description>
            <ChildElements>
                <Element name="Tag">
                    <Description>Tag of a post.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the tag.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
                        <Element name="Name">
                            <Description>Tag name.</Description>
                        </Element>
                        <Element name="Date_Created">
                            <Description>Tag creation date.</Description>
                        </Element>
                        <Element name="Is_Good">
                            <Description>Tag validation for relevance to the movie theme.</Description>
                        </Element>
                        <Element name="Author">
                            <Description>User identifier who created the tag.</Description>
                        </Element>
                        <Element name="Post_ID">
                            <Description>Post identifier for the tag.</Description>
                        </Element>
                    </ChildElements>
                </Element>
            </ChildElements>
        </Element>

        <Element name="Logs">
            <Description>Contains logs of user actions in the system.</Description>
            <ChildElements>
                <Element name="Log">
                    <Description>Record of a user action.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the log entry.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
                        <Element name="Date_Created">
                            <Description>Timestamp of when the action was logged.</Description>
                        </Element>
                        <Element name="Action">
                            <Description>Description of the user action.</Description>
                        </Element>
                        <Element name="User_ID">
                            <Description>Identifier of the user who performed the action.</Description>
                        </Element>
                        <Element name="Details">
                            <Description>Additional details about the action.</Description>
                        </Element>
                    </ChildElements>
                </Element>
            </ChildElements>
        </Element>

        <Element name="Movies">
            <Description>Contains information about movies.</Description>
            <ChildElements>
                <Element name="Movie">
                    <Description>Movie in the database.</Description>
                    <Attributes>
                        <Attribute name="id">
                            <Type>ID</Type>
                            <Required>true</Required>
                            <Description>Unique identifier for the movie.</Description>
                        </Attribute>
                    </Attributes>
                    <ChildElements>
